// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_on_widgets
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // =========================================================================
  // يجب استبدال القيم التالية بالقيم الحقيقية من مشروعك في Firebase Console
  // =========================================================================

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_REAL_ANDROID_API_KEY_HERE', // من إعدادات المشروع > مفاتيح الويب
    appId: 'YOUR_REAL_ANDROID_APP_ID_HERE', // من إعدادات التطبيق في Firebase
    messagingSenderId: 'YOUR_REAL_MESSAGING_SENDER_ID_HERE', // من إعدادات المشروع > السحابة والمراسلة
    projectId: 'YOUR_REAL_PROJECT_ID_HERE', // من إعدادات المشروع > عام
    storageBucket: 'YOUR_REAL_STORAGE_BUCKET_HERE', // من إعدادات المشروع > عام
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_REAL_IOS_API_KEY_HERE',
    appId: 'YOUR_REAL_IOS_APP_ID_HERE',
    messagingSenderId: 'YOUR_REAL_MESSAGING_SENDER_ID_HERE',
    projectId: 'YOUR_REAL_PROJECT_ID_HERE',
    storageBucket: 'YOUR_REAL_STORAGE_BUCKET_HERE',
    iosBundleId: 'YOUR_REAL_IOS_BUNDLE_ID_HERE',
  );
}
